### ISSUE TITLE
Question about the experiment result.

### ISSUE THREAD

**Issue by Ramlinbird** [easezyc/MetaHeac#1]
Hello, sorry to disturb you. I want to ask if you have compared the experiment result with 2018's submit results? Because I found that many participants reported the auc aboce 0.75, which is much higher than the aucs listed in the paper. Why?

**Comment by easezyc** [comment]
I did not reproduce the best result of the competition. In a competition, ensemble methods, feature engineer, and parameter searching are necessary, but the methods has no help for my research. I just need keep a fair comparison for all methods. In addition, I divided the dataset by myself which could be also different to the competition.
